### ISSUE TITLE
Config generator for groovy broken

### ISSUE THREAD

**Issue by stonier** [ros-windows/win_ros#40]
Someone had troubles with this - got mixed up with hydro?

http://wiki.ros.org/win_ros/groovy/Msvc%20Overlays?action=diff&rev1=7&rev2=8

Make sure the wiki page is updated afterwards as well.

**Comment by stonier** [comment]
Groovy and hydro instructions are using the same version of win_python_build_tools.
- http://wiki.ros.org/win_ros/groovy/Msvc%20SDK
- http://wiki.ros.org/win_ros/hydro/Msvc%20SDK

They need to be separate - i.e. groovy installation doesn't use hydro tracks. Maybe 0.2.4 for groovy and 0.2.5 for hydro?

**Comment by flaviofontana** [comment]
Hi as they seem to be distro depended can we reflect this in the name?
For example in http://files.yujinrobot.com/win_ros/sdk/ i could pick the right one just by looking at the names.
In addition yesterday i found that also the winros_create_msg_pkg did not produce the correct package.xml and CMakeLists.txt, however after manually updating it worked.

At this moment im using an overlayed workspace in which i have my messages the i can use winros_make to compile them. However my program I develop in Mscv without the CMakeList.txt. Is this the way you guys do it as well?

thanks for you help
flavio

**Comment by stonier** [comment]
That's a good idea. 

Let's symlink win_python_build_tools-<rosdistro>.exe to a particular version for both groovy and hydro.

**Comment by stonier** [comment]
For generating headers, yes, that is currently the way we do it. You could of course save those headers somewhere (e.g. github repo) to save from having to recreate them. Even run a jenkins CI job to recreate the latest headers every night to automate things a bit for your team.

**Comment by yichoe** [comment]
win_python_build_tools for Groovy is different with it for Hydro.
- http://wiki.ros.org/win_python_build_tools/groovy
- http://wiki.ros.org/win_python_build_tools/hydro

The build tool version is 0.2.2 for Groovy and 0.2.5 for Hydro currently. These are linked in each pages.

**Comment by yichoe** [comment]
winros_create_pkg and winros_create_msg_pkg of Groovy version have the error. This is fixed in [Hydro](https://github.com/ros-windows/win_ros/commit/3600ace0042c4d0ac1e50aa1e2f43436a9e63009). You can find an example for winros_create_msg_pkg in [Msvc SDK Messages](http://wiki.ros.org/win_ros/hydro/Msvc%20SDK%20Messages).

**Comment by flaviofontana** [comment]
Hi yichoe 
thanks for your answer

So i will then update the wiki page and refer to the 0.2.2 version. Sorry did not understand; is the bug still existent in groovy when using 0.2.2, if yes do you plan on fixing it?  

flavio

**Comment by yichoe** [comment]
Yes, the bug(winros_create_msg_pkg) is still exist in Groovy. Do you have special reason for using Groovy instead of Hydro?

**Comment by flaviofontana** [comment]
thanks again for the reply. 
My lab just migrated to groovy like two weeks ago, its hard to push them;-). So my suggestion is the following:
- I will update the groovy doku to mention the bug and refer to the correct build tools 0.2.2
- I add the info on how to manually create a message with groovy.
- I will test hydro (will take me probably a week) then I contribute to the hydro documentation the points that were not clear to me. 
  Thanks and have a good day.

**Comment by stonier** [comment]
That would be good to have fixed in groovy, shouldn't take too much effort. 

flaviofontana, if you want to attack it quickly, you can probably also easily hack the template files that get installed and send us them for groovy once you've tested them. That would certainly be easier than testing and moving your lab to hydro.

Having said that, if you're upgrading your lab right now I would recommend hydro. Groovy was a huge update since it was the first mass implementation release for catkin, Hydro is a stabilisation of that change.
